export const ROUTES = {
  home: '/',
  machines: '/machines',
  machineDetail: '/machines/:id',
  machineBooking: '/machines/:id/booking',
  booking: '/booking',
  cart: '/cart',
  checkout: '/checkout',
  purchase: '/purchase',
  paymentSuccess: '/payment/success',
  paymentFailed: '/payment/failed',
  paymentHistory: '/payments/history',
  billing: '/billing',
  orderSuccess: '/order-success',
  orders: '/orders',
  orderDetail: '/orders/:id',
  profile: '/profile',
  login: '/login',
  register: '/register',
  notFound: '*',
} as const;
