export const ROUTES = {
  home: '/',
  auth: '/auth',
  machines: '/machines',
  providerMachines: '/providers/:providerId/machines',
  machineDetail: '/machines/:id',
  machineBooking: '/machines/:id/booking',
  booking: '/booking',
  cart: '/cart',
  checkout: '/checkout',
  orderSuccess: '/order-success',
  account: '/account',
  orders: '/orders',
  orderDetail: '/orders/:id',
  profile: '/profile',
  login: '/login',
  register: '/register',
  notFound: '*',
} as const;
